### ISSUE TITLE
Small user guide typos

### ISSUE THREAD

**Issue by Sam-Vervaeck** [stnolting/neorv32#1003]
> Listing 5. Example: override default RAM size while invoking make
> $ make USER_FLAGS+="-Wl,--defsym,__neorv32_rom_size=16k" clean_all exe

In section 3.2 it should be `__neorv32_ram_size` instead I suppose on the second line?

> program to be executed must be compiled and installe using the install makefile target. Next, the

In the new packaging disclaimer you added, it should be `installed`.

**Comment by stnolting** [comment]
Thanks! I'll fix that!
