### ISSUE TITLE
Zephyr RTOS  URL needs update

### ISSUE THREAD

**Issue by cryptobharathi** [stnolting/neorv32#1088]
The URL pointing to Zephyr RTOS in README (https://github.com/stnolting/neorv32) is `https://docs.zephyrproject.org/latest/boards/riscv/neorv32/doc/index.html ` is modified in Zephyr RTOS documentation page, which needs to be updated to `https://docs.zephyrproject.org/latest/boards/others/neorv32/doc/index.html`

<img width="911" alt="image" src="https://github.com/user-attachments/assets/f5398c95-ac7f-483b-beab-f24ff1d5e88a">

**Comment by stnolting** [comment]
Thanks for the hint!
I'll fix that (or do you want to make a PR? :wink:).

**Comment by stnolting** [comment]
Fixed.

**Comment by cryptobharathi** [comment]
> Thanks for the hint! I'll fix that (or do you want to make a PR? 😉).

Its a small observation, so i feel direct fix is better than PR :) 

Happy to see, its fixed and closed 👍
