### ISSUE TITLE
Third party build cannot be uploaded

### ISSUE THREAD

**Issue by AbdulrahmanKH7** [stnolting/neorv32#179]
Hello Stephan,
I hope you are well.

I managed to build the blink_led example on Segger's EmbeddeStudio, however when I upload it to NEORV32 via UART I receive error_0 which is related to the executable signature. Is there a way to resolve this? Is this approach actually valid? I used the settings you recommend like ilp32 ABI and rv32i in the IDE and used your linker and startup file also in the IDE.

Thanks a lot!

**Comment by AbdulrahmanKH7** [comment]
I am using ARM-USB-TINY-H adapter.
I will try to add the -d flag and see what happens
Many thanks 👍

**Comment by emb4fun** [comment]
Do you have still problems to get the blink_led examples running on "Segger Embedded Studio for RISC-V"?
I could successful get it to work. But you must have to use a J-Link.

Regards,
Michael

**Comment by AbdulrahmanKH7** [comment]
> 
> 
> Do you have still problems to get the blink_led examples running on "Segger Embedded Studio for RISC-V"? I could successful get it to work. But you must have to use a J-Link.
> 
> Regards, Michael

Hi,
Thanks for reaching out. I tried with the J-link and it failed also. Do you use any special settings in the IDE?

**Comment by AbdulrahmanKH7** [comment]
I think my ARM-USB-TINY-H adapter does not support the J-link. What debugger adapter did you use?
Best regards

**Comment by emb4fun** [comment]
The Segger Embedded Studio works **only** with a J-Link.

**Comment by stnolting** [comment]
@AbdulrahmanKH7 

The on-chip debugger's "debug transfer module" (the actual JTAG "PHY") has been reworked (#216) because there were some timing issues in the external interface. That's why the Jlink EDU could not connect to the chip. Maybe this was also the cause of your troubles with your debugger.

**Comment by stnolting** [comment]
I think this can be closed. Feel free to open another issue if you have further questions/problems.
