### ISSUE TITLE
Does Neorv32 support Altera DE2 with Cyclone II ?

### ISSUE THREAD

**Issue by ralphnguyen86** [stnolting/neorv32#187]
I have an Altera DE2 with Cyclone II dev board which was bought more than 10 years ago.  Does Neorv32 support it ?

**Comment by stnolting** [comment]
Older versions of Quartus (that still support Cyclone II) have problems with inferring block RAM from the **default** memory descriptions (see #197). We have added alternative memory components in [`rtl/core/mem`](https://github.com/stnolting/neorv32/tree/master/rtl/core/mem) that work with these legacy Quartus versions (see #198).

**Comment by emb4fun** [comment]
Yes, the NEORV32 also runs on a Cyclone II. An example for an Altera DE1 board can be found here: 

https://github.com/emb4fun/neorv32-examples

Take a look for de1-neorv32-sdram-qsys. This is a simple example using on-chip RAM as memory
for IMEM and DMEM. In addition, there is the SDRAM which can be addressed by the Wishbone to
Avalon Master in the Qsys area.

**Comment by stnolting** [comment]
@ralphnguyen86 
I think this can be closed, right?

**Comment by ralphnguyen86** [comment]
@stnolting thank you very much.
