### ISSUE TITLE
neorv32_cpu_get_cycle() always returns zero

### ISSUE THREAD

**Issue by AWenzel83** [stnolting/neorv32#19]
I just created a new project using the script in the boards folder. The bitstream is generated as expected and the bootloader is working. But when testing the blink-example, nothing happens.

After some investigation I realized, that the function 
`neorv32_cpu_get_cycle();`
always returns zero, and therefore the function
`neorv32_cpu_delay_ms(200);`
used in the blink-example never returns.

The behaviour is the same for the ARTY and the NEXYS examples.

**Comment by stnolting** [comment]
Oh crap!
Seems like my last modifications of `crt0.S` had some side effects I did not consider...
Right now, `ctr0` sets all bits of the `mcountinhibt` CSR so **all counters are stopped** until they are explicitly enabled by writing zero to the according `mcountinhibt` bit.
I will fix that.

Thanks for the hint!

**Comment by stnolting** [comment]
Should be fixed now.

**Comment by AWenzel83** [comment]
It works again, great. I guess this issue may be closed now.
