### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by SOUMYADIPSAHA10** [stnolting/neorv32#203]
Hello,
Can this core be able to run Linux on it?

**Comment by umarcor** [comment]
See https://github.com/stnolting/neorv32/pull/194#issuecomment-961579351.

**Comment by stnolting** [comment]
As discussed in #194 the processor cannot run Linux out of the box (at least not without virtualization) because the CPU lacks a memory management unit and support for supervisor operation mode. However, you can run embedded real-time operating system like FreeRTOS or Zephyr OS.

**Comment by stnolting** [comment]
I think this can be closed, right?
