### ISSUE TITLE
[idea] add WaveDrom support for AsciiDoc documentation

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#265]
Most of the figures used in the documentation (mainly waveforms) are made with [WaveDrom](https://wavedrom.com/). It is possible to add those WaveDrom scripts right into the AsciiDoc source files of the projects documentation (requiring a modification of the docs's build scripts).

I think this has also been discussed somewhere, but I cannot find that... Anyway, I think it would be great to have this all-in-one setup as this would also add the wavefrom sources to the project (which are not available yet). :+1:

**Comment by umarcor** [comment]
See branch https://github.com/umarcor/neorv32/tree/feat/docs/wavedrom-demo. I've been keeping it, waiting for this issue :smile: See this dialogue we had in may: https://github.com/stnolting/neorv32/pull/40
