### ISSUE TITLE
🧪 support for constructors & destructors

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#322]
@jpf91 @GideonZ

Triggered by the discussion in #313:

Support for constructors and destructors could be "easily" added by extending the `.text` section of the default NEORV32 [linker script](https://github.com/stnolting/neorv32/blob/main/sw/common/neorv32.ld) (provided by @GideonZ):

```
    /* .preinit_array */
    PROVIDE_HIDDEN (__preinit_array_start = .);
    KEEP (*(.preinit_array*))
    PROVIDE_HIDDEN (__preinit_array_end = .);

    /* .init_array */
    PROVIDE_HIDDEN (__init_array_start = .);
    KEEP (*(SORT(.init_array.*)))
    KEEP (*(.init_array*))
    PROVIDE_HIDDEN (__init_array_end = .);

    /* .fini_array */
    PROVIDE_HIDDEN (__fini_array_start = .);
    KEEP (*(SORT(.fini_array.*)))
    KEEP (*(.fini_array*))
    PROVIDE_HIDDEN (__fini_array_end = .);
```
Adding this to the linker script does not hurt as the linker will remove all the included functions if they are not explicitly called.

The con-/destructor array of function pointers have to be called from [`crt0`](https://github.com/stnolting/neorv32/blob/main/sw/common/crt0.S) before and after `main` is calles, respectively:

```
call __libc_init_array
...
call __libc_fini_array
```

For **plain C** code it is very unlikely that there are any constructors or destructors at all unless explicitly defined, for example:

```c
void __attribute__((constructor)) test_constructor(void) {
  neorv32_uart1_setup(19200, PARITY_NONE, FLOW_CONTROL_NONE);
  neorv32_uart1_printf("\nHello CONstructor!\n\n");
}

void __attribute__((destructor)) test_destructor(void) {
  neorv32_uart1_setup(19200, PARITY_NONE, FLOW_CONTROL_NONE);
  neorv32_uart1_printf("\nHello DEstructor!\n\n");
}
```

Adding function calls to `__libc_init_array` and `__libc_fini_array` would add some code/library overhead even if there are not constructors/destructors at all.

I am not sure if this should be added to the current setups, which targets plain C code. One option would be to make "define switches" for the according functions calls so the user can explicitly enable this functionality when compiling an application. Another option would be to call the `__libc_init_array` and `__libc_fini_array` function directly form `main` (in C code) is they are required.

I am not sure about c++ applications at all - I have never tested that because I am not really familiar with that. What do you think??

**Comment by GideonZ** [comment]
Hi Stephan...  Shall I just create a pull request with some minor changes
to the linker script and to the crt0.s to support constructors? Maybe a
tiny C++ example?
