### ISSUE TITLE
Does Neorv32 support trace feature?

### ISSUE THREAD

**Issue by lapnd** [stnolting/neorv32#439]
Hi,
I tried to find in source code to see if neorv32 support trace feature but I haven't found yet.
Do we have this feature with Neorv32?

**Comment by stnolting** [comment]
Hey there!

There is no hardware to support the [RISC-V trace spec](https://github.com/riscv-non-isa/riscv-trace-spec) (yet).

The trace system is quite complex and so far I did not see any need for that as the on-chip debugger was always sufficient for most needs (at least for me :wink:). Furthermore, you can always do a simulation that will give you _all_ relevant data - obviously this is no suitable replacement for doing "real-word" analysis.

**Comment by lapnd** [comment]
Thank you @stnolting
