### ISSUE TITLE
Re-integrate UART hardware flow control

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#540]
### Discussed in https://github.com/stnolting/neorv32/discussions/537

<div type='discussions-op-text'>

<sup>Originally posted by **vhdlnerd** March  8, 2023</sup>
I'm disappointed with the recent removal of the UART hardware handshaking lines.  This breaks all my neorv32 based designs. I'm a little shocked that functionality would be removed from a basic interface.  I use the UARTs at 921600 baud sending commands to the neorv32 that take time to process -- hardware handshake lines are required to avoid dropping commands.

The two workarounds mentioned in the change notes (adding a non-crippled UART as a custom function or a wishbone module) are equally poor. Either way means having a custom bootloader and worst not being able to use any of neov32's SW library functions that uses UARTs (neorv32_uart_printf, ...).

Brian</div>

**Comment by vhdlnerd** [comment]
Thanks for adding this back in!
