### ISSUE TITLE
sw/lib/source/neorv32_rte.c

### ISSUE THREAD

**Issue by Arun789788** [stnolting/neorv32#563]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Environment:**
 - OS
 - GCC Version (RISC-V and native)
 - Libraries used (clib, newlib, ...)

**Hardware:**
 - Hardware version (x.x.x.x)
 - Implemented CPU extensions, peripherals, ...
 - Hardware modifications

**Additional context**

**Comment by Arun789788** [comment]
My address country India jila Sultanpur post kamtaganj gram basti paharpur Narsinghpur my name is Arun bihari
Google bug sw/lib/source/neorv32_rte.c

**Comment by stnolting** [comment]
Was this just a mistake?
