### ISSUE TITLE
Strange TRAP in strange circumstances

### ISSUE THREAD

**Issue by agamez** [stnolting/neorv32#621]
Hi!

I'm facing a pretty strange problem and I guess it must be a neorv32 bug (although I guess it could also be a compiler one). I will need some time to collect all the information and produce a minimum failing example so I can post the whole code which is pretty big right now, but I want to start reporting it with what I know right now in case the issue is easy to spot.

I'm writing a kind-of OOP infrastructure for my projects in C with the usual struct with pointers to functions and the like. Now, when I call one of these callback functions which is pretty ridiculous if you ask me.

Please disregard this issue until I can trace exactly where the problem lies as I've just made some discoveries and don't want anyone to lose their time reading all this when it doesn't make much sense!

**Comment by stnolting** [comment]
FTR: Continued in #623
