### ISSUE TITLE
Passing argument to ghdl_sim.sh - bug?

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#70]
@umarcor 

Currently, the [`riscv-arch-test`](https://github.com/stnolting/neorv32/actions/workflows/riscv-arch-test.yml) worklfow does not work.

I think there might be a problem here:

https://github.com/stnolting/neorv32/blob/b53feb7f6db68dd0ae8b6ca48f9ef44cbc29aa11/sim/ghdl/ghdl_sim.sh#L19-L24

When passing the max. simulation time from a makefile, `SIM_CONFIG` does not seem to be updated globally.

https://github.com/stnolting/neorv32/blob/b53feb7f6db68dd0ae8b6ca48f9ef44cbc29aa11/riscv-arch-test/port-neorv32/framework_v2.0/riscv-target/neorv32/device/rv32i_m/I/Makefile.include#L36

Hence the simulation runs for the default time (8ms) - which would take ages for the `riscv-arch-test` to complete. When I use the code below for `ghdl_sim.sh` it seems to work.

```bash
if [ -z $1 ]
then
  echo "Using default simulation config: $SIM_CONFIG"
else
  echo $1;
  SIM_CONFIG=$1;
  echo "Using user simulation config: $SIM_CONFIG";
fi
```

I am not a bash expert, though. Where is the difference? Does the updated code do anything that my workaround does not?! 🤔

**Comment by umarcor** [comment]
@stnolting, my bad. I didn't realise that SIM_CONFIG is kept local. I guess we can either export it in L22, or change it to your style. As you wish.

**Comment by stnolting** [comment]
No problem!
I will update that. Hopefully nothing else breaks 😅
