### ISSUE TITLE
Atomic accesses documentation error

### ISSUE THREAD

**Issue by nicobld** [stnolting/neorv32#751]
There is an inconsistency in the documentation about atomic access :
https://stnolting.github.io/neorv32/#_atomic_accesses

![image](https://github.com/stnolting/neorv32/assets/95432566/f0d13a72-dca3-4197-81f3-c44d98e335c5)

It says :
_The successful operation is indicated by a 1 being returned via the rsp.data_
_The failed operation is indicated by a 0 being returned via the rsp.data_
Which isn't the same as shown on the waves.

**Comment by stnolting** [comment]
You are right - the figure is correct but the text is not. I'll fix that.
Thanks for finding this!

**Comment by stnolting** [comment]
Fixed! :wink:
