### ISSUE TITLE
Neorv32 synthesis in Design compiler

### ISSUE THREAD

**Issue by mahdi259** [stnolting/neorv32#884]
Hi,
This is actually a question. I have synthesized Neorv32 in Design Compiler. My problem is with the resulting design file that I produce with design compiler. It actually gives 'X' signal in simulation for some outputs. Have you ever synthesized Neorv32 in Design compiler @stnolting?
Thanks

**Comment by mahdi259** [comment]
Yes, I synthesized the same neorv32_top that I used in neorv32_tb_simple. The UART signals are getting 'X'. If I solve it, I will describe that here.

**Comment by mahdi259** [comment]
The problem was with hold time of implementation. I relaxed the constraints and it worked.

**Comment by stnolting** [comment]
Great to hear! :+1:

**Comment by mahdi259** [comment]
Hi @stnolting 
Do you have a friend that is familiar with synopsis DC?

**Comment by stnolting** [comment]
Unfortunately not. 🙈
But maybe someone else here can help?!

**Comment by mahdi259** [comment]
Ok thanks

**Comment by mahdi259** [comment]
For anyone who reads this later. Generating sdf file of synthesized design and using it for simulation in Questasim improves maximum operational frequency of design.
