### ISSUE TITLE
Datasheet error in the DMA section

### ISSUE THREAD

**Issue by Sam-Vervaeck** [stnolting/neorv32#968]
**Describe the bug**
The descriptions of the DMA_TTYPE_QSEL does not match over two locations:
![image](https://github.com/user-attachments/assets/faf45ad2-8bc8-41bc-9495-794a38ace362)
![image](https://github.com/user-attachments/assets/2b9a17db-3641-48b6-afdd-015fda919244)

**Expected behavior**
I assume the first screenshot is the correct description and should be carried over.

**PS:**
I am putting this here now as a bug, do you prefer if I create a discussion for it instead like in the past?

**Comment by Sam-Vervaeck** [comment]
To add another error since opening another ticket seems unnecessary, this figure seems to be misplaced right now:
![image](https://github.com/user-attachments/assets/be64922a-8e39-44b3-8bd6-40071292f443)

**Comment by Sam-Vervaeck** [comment]
I want to stress though that the general quality of documentation is really good. Working with this project has been a breeze compared to trying to work with Ibex previously!

**Comment by stnolting** [comment]
Thanks for finding these!

> I want to stress though that the general quality of documentation is really good. Working with this project has been a breeze compared to trying to work with Ibex previously!

Thank you very much! :)
