### ISSUE TITLE
Small error in the datasheet

### ISSUE THREAD

**Issue by Sam-Vervaeck** [stnolting/neorv32#988]
Under 3.7.1. it says:

> The NEORV32 CFU uses the custom-1 and custom-2 opcodes to identify the instruction implemented 

This should be custom-0 and custom-1 as in the rest of the datasheet?

**Comment by stnolting** [comment]
> This should be custom-0 and custom-1 as in the rest of the datasheet?

Right. I'll fix that. Thanks for spotting this!
